export const data = [
    {
      id: 1,
      link: "song1.mp3",
      genre: "Underground Rap",
      track: "SystemPreferences",
      artist: "Bones", 
      year: 2017,
    },
    {
      id: 2,
      link: "song2.mp3",
      genre: "Underground Rap",
      track: "Oxygen",
      artist: "Bones",
      year: 2017,
    },
    {
      id: 3,
      link: "song3.mp3",
      genre: "Hip-Hop/Rap",
      track: "Phantom Menace",
      artist: "$UICIDEBOY$",
      year: 2018,
    },
    {
      id: 4,
      link: "song4.mp3",
      genre: "Hip-Hop/Rap",
      track: "Fuck",
      artist: "$UICIDEBOY$",
      year: 2017,
    },
    {
      id: 5,
      link: "song5.mp3",
      genre: "Rap",
      track: "Questioning Your Theory",
      artist: "Night Lovell",
      year: 2014,
    },
    {
      id: 6,
      link: "song6.mp3",
      genre: "Rap",
      track: "Barbie Doll",
      artist: "Night Lovell",
      year: 2016,
    },
    {
      id: 7,
      link: "song7.mp3",
      genre: "Rap",
      track: "Call Me Water",
      artist: "Night Lovell",
      year: 2021,
    },
  ];